blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<pk>/', views.PostDetailView.as_view(), name='post'),
    path('<pk>/update', views.PostUpdateView.as_view(), name='update'),
    path('<pk>/comment', views.CommentCreateView.as_view(), name='comment'),
]

djangox_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from users.models import CustomUser


class Author(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, related_name='author')
    bio = models.TextField()

    def __str__(self):
        return f'{self.author.username}'


class Post(models.Model):
    title = models.CharField(max_length=200, help_text='Enter your post title here.')
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, related_name='posts')
    content = models.TextField(help_text='Enter your blog post here.')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = (('can_create_post', 'can_create_post'),)
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.title} by {self.author.author.username}'


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, related_name='comments', null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', help_text='Enter your blog post here.')
    content = models.TextField(help_text='Enter your comment here.')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.content[:100]}'

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.post.pk})

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

blog/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from blog.models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

    def clean_title(self):
        data = self.cleaned_data['title']

        # check if title is more than 64 characters
        if len(data) > 128:
            raise ValidationError('Title cannot be more than 128 characters.')
        return data

    def clean_content(self):
        data = self.cleaned_data['content']

        # check if title is more than 3000 characters
        if len(data) > 3000:
            raise ValidationError('Content cannot be more than 300 characters.')
        return data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def clean_content(self):
        data = self.cleaned_data['content']
        # check if title is more than 3000 characters
        if len(data) > 512:
            raise ValidationError('Content cannot be more than 300 characters.')
        return data

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect


from blog.models import Post
from blog.forms import CommentForm, PostForm


class PostListView(ListView):
    template_name = 'pages/home.html'
    context_object_name = 'posts'
    model = Post


class PostDetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user and self.request.user.is_authenticated:
            context['form'] = CommentForm()
        return context


class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'blog/create.html'
    model = Post
    form_class = PostForm
    permission_required = 'blog.can_create_post'

    def form_valid(self, form):
        form.instance.author = self.request.user.author.first()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'blog/update.html'
    model = Post
    form_class = PostForm
    context_object_name = 'post'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author.author != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class CommentCreateView(LoginRequiredMixin, CreateView):
    form_class = CommentForm
    http_method_names = ['post']

    def form_invalid(self, form):
        post = Post.objects.get(pk=self.kwargs['pk'])
        messages.error(self.request, 'Comment not created.')
        return redirect(post.get_absolute_url())

    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs['pk'])
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.post = post
        comment.save()
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView
from blog.models import Post


class HomePageView(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()[:5]

        return context


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

users/views.py
from django.shortcuts import render

# Create your views here.

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<title>{% block title %}DjangoX{% endblock title %}</title>
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

{% block css %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'home' %}">DjangoX</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.email }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="alert alert-{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
  <div class="container">
    {% block content %}
      <p>Default content...</p>
    {% endblock content %}
  </div>

   <nav class="navbar fixed-bottom navbar-dark bg-dark">
    <a class="navbar-brand" href="#">&copy; DjangoX 2018</a>
  </nav>

  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <!-- 3rd party JavaScript -->

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>
</html>

templates/blog/create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create Post</h1>
    <form action="{% url 'blog:create' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">Post</button>
    </form>
{% endblock %}

templates/blog/detail.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>

    <ul>
        {% for comment in post.comments.all %}
            <li>
                <p>{{ comment.content }}</p>
                <small>{{ comment.user.username }}</small>
            </li>
        {% endfor %}
    </ul>
    {% if form %}
    <!--- HTML5 validator needed to prevent post request -->
    <form action="{% url 'blog:comment' pk=post.pk %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">Comment</button>
    </form>
    {% endif %}
{% endblock %}

templates/blog/update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <form action="{% url 'blog:create' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">Post</button>
    </form>
{% endblock %}

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<img id="hero" src="{% static 'images/falconx.png' %}" class="img-fluid mx-auto" alt="FalconX launch"/>
{% for post in posts %}
    <a href="{% url 'blog:post' pk=post.pk %}">{{ post.title }}</a>
    <p>{{ post.content|truncatechars:128}}</p>
{% endfor %}
{% endblock content %}